name: tree-detection
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - asn1crypto=1.3.0=py37_0
  - attrs=19.3.0=py_0
  - blas=1.0=mkl
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2019.11.28=hecc5488_0
  - certifi=2019.11.28=py37hc8dfbb8_0
  - cffi=1.14.0=py37h7a1dbc1_0
  - cfitsio=3.470=he774522_2
  - chardet=3.0.4=py37_1003
  - click=7.0=py37_0
  - click-plugins=1.1.1=py_0
  - cligj=0.5.0=py37_0
  - cloudpickle=1.3.0=py_0
  - cryptography=2.8=py37h7a1dbc1_0
  - curl=7.68.0=h2a8f88b_0
  - cycler=0.10.0=py37_0
  - cytoolz=0.10.1=py37he774522_0
  - dask-core=2.10.1=py_0
  - decorator=4.4.1=py_0
  - expat=2.2.5=he025d50_0
  - fiona=1.8.11=py37h737a305_0
  - freetype=2.9.1=ha9979f8_1
  - freexl=1.0.5=hfa6e2cd_0
  - gdal=3.0.2=py37h2fee047_7
  - geoalchemy2=0.6.3=py_0
  - geopandas=0.7.0=py_1
  - geos=3.8.0=h33f27b4_0
  - geotiff=1.5.1=h5770a2b_0
  - gettext=0.19.8.1=hb01d8f6_1002
  - glib=2.58.3=py37hc0c2ac7_1002
  - hdbscan=0.8.24=py37hc8d92b1_1
  - hdf4=4.2.13=h712560f_2
  - hdf5=1.10.5=nompi_ha405e13_1104
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=64.2=he025d50_1
  - idna=2.8=py37_0
  - imageio=2.6.1=py37_0
  - intel-openmp=2019.4=245
  - joblib=0.14.1=py_0
  - jpeg=9c=hfa6e2cd_1001
  - jsoncpp=1.8.4=h1ad3211_1002
  - kealib=1.4.10=hf7dc31f_1005
  - kiwisolver=1.1.0=py37ha925a31_0
  - kneed=0.5.1=py_0
  - krb5=1.17.1=hc04afaa_0
  - laszip=3.4.0=h6538335_0
  - laz-perf=1.3.0=h6538335_1002
  - libblas=3.8.0=14_mkl
  - libboost=1.67.0=hd9e427e_4
  - libcblas=3.8.0=14_mkl
  - libcurl=7.68.0=h2a8f88b_0
  - libffi=3.2.1=h6538335_1006
  - libgdal=3.0.2=ha9114c6_7
  - libiconv=1.15=h1df5818_7
  - libkml=1.3.0=he5f2a48_4
  - liblapack=3.8.0=14_mkl
  - libnetcdf=4.7.3=nompi_hc957ea6_101
  - libpng=1.6.37=h2a8f88b_0
  - libpq=12.2=h3235a2c_0
  - libspatialindex=1.9.3=h33f27b4_0
  - libspatialite=4.3.0a=h7ffb84d_0
  - libssh2=1.8.2=h7a1dbc1_0
  - libtiff=4.1.0=h21b02b4_3
  - libwebp=1.0.2=hfa6e2cd_5
  - libxml2=2.9.10=h9ce36c8_0
  - libxslt=1.1.33=h579f668_0
  - lxml=4.5.0=py37h1350720_0
  - lz4-c=1.8.3=he025d50_1001
  - m2w64-expat=2.1.1=2
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gettext=0.19.7=2
  - m2w64-gmp=6.1.0=2
  - m2w64-libiconv=1.14=6
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - m2w64-xz=5.2.2=2
  - matplotlib=3.1.2=py37h64f37c6_0
  - mkl=2019.4=245
  - mkl-service=2.3.0=py37hb782905_0
  - msys2-conda-epoch=20160418=1
  - munch=2.5.0=py_0
  - networkx=2.4=py_0
  - nitro=2.7.dev6=he025d50_1
  - numpy=1.18.1=py37hc71023c_0
  - olefile=0.46=py37_0
  - openjpeg=2.3.1=h57dd2e7_3
  - openssl=1.1.1d=hfa6e2cd_0
  - owslib=0.18.0=py_0
  - packaging=20.1=py_0
  - pandas=0.25.1=py37he350917_0
  - pcre=8.43=ha925a31_0
  - pdal=2.0.1=py37h1d384ee_9
  - pillow=7.0.0=py37hcc1f983_0
  - pip=20.0.2=py37_1
  - poppler=0.67.0=h1707e21_8
  - poppler-data=0.4.9=1
  - postgresql=12.2=h3235a2c_0
  - proj=6.2.1=h9f7ef89_0
  - psycopg2=2.8.4=py37hb32ad35_1
  - py=1.8.1=py_0
  - pycparser=2.19=py37_0
  - pyopenssl=19.1.0=py37_0
  - pyparsing=2.4.6=py_0
  - pyproj=2.4.2.post1=py37h9716dcf_0
  - pyqt=5.9.2=py37h6538335_2
  - pysocks=1.7.1=py37_0
  - python=3.7.6=h5b45d93_2
  - python-dateutil=2.8.1=py_0
  - python-pdal=2.2.2=py37hdc08f70_1
  - python_abi=3.7=1_cp37m
  - pytz=2019.3=py_0
  - pywavelets=1.1.1=py37he774522_0
  - qt=5.9.7=h506e8af_3
  - requests=2.22.0=py37_1
  - retry=0.9.2=py_0
  - rtree=0.9.3=py37h21ff451_0
  - scikit-image=0.16.2=py37h47e9c7a_0
  - scikit-learn=0.21.2=py37h7208079_1
  - scipy=1.4.1=py37h9439919_0
  - setuptools=45.2.0=py37_0
  - shapely=1.7.0=py37h2130f3d_0
  - sip=4.19.8=py37h6538335_0
  - six=1.14.0=py37_0
  - sqlalchemy=1.3.13=py37he774522_0
  - sqlite=3.31.1=he774522_0
  - tbb=2018.0.5=he980bc4_0
  - tiledb=1.7.0=hffbbd95_2
  - tk=8.6.8=hfa6e2cd_0
  - toolz=0.10.0=py_0
  - tornado=6.0.3=py37he774522_3
  - urllib3=1.25.8=py37_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_1
  - wheel=0.34.2=py37_0
  - win_inet_pton=1.1.0=py37_0
  - wincertstore=0.2=py37_0
  - xerces-c=3.2.2=ha925a31_0
  - xz=5.2.4=h2fa13f4_4
  - zlib=1.2.11=h62dcd97_3
  - zstd=1.4.4=hd8a0e53_1
prefix: C:\Users\arnot\AppData\Local\Continuum\anaconda3\envs\tree-detection

